version: "3.9"

services:

  db:
    image: postgres:17
    container_name: atlas_db
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aitbek
      POSTGRES_DB: atlas_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: atlas_redis
    restart: always

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    container_name: atlas_minio
    restart: always

    command: server /data --console-address ":9001"

    environment:
      MINIO_ROOT_USER: atlas
      MINIO_ROOT_PASSWORD: atlaspassword

    ports:
      - "9000:9000"
      - "9001:9001"

    volumes:
      - minio_data:/data

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: atlas_api
    restart: always

    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy

    expose:
      - "8000"

    env_file:
      - .env.docker

  nginx:
    build: ./nginx
    container_name: atlas_nginx
    restart: always

    depends_on:
      - api

    ports:
      - "80:80"

volumes:
  postgres_data:
  redis_data:
  minio_data:
