"""add refresh tokens

Revision ID: 0989a66c8a4d
Revises: 39a1731c7910
Create Date: 2026-07-16 12:38:35.726951

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "0989a66c8a4d"
down_revision: Union[str, Sequence[str], None] = "39a1731c7910"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
