"""add status to jobs

Revision ID: 16bbf1f99b32
Revises: 7d8392a7960e
Create Date: 2026-07-12 21:22:18.544386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16bbf1f99b32'
down_revision: Union[str, Sequence[str], None] = '7d8392a7960e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'message')
    op.add_column('jobs', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('jobs', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'updated_at')
    op.drop_column('jobs', 'status')
    op.add_column('applications', sa.Column('message', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
