"""add refresh tokens

Revision ID: 39a1731c7910
Revises: 6c4b796bd8ff
Create Date: 2026-07-16 12:36:30.542107

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "39a1731c7910"
down_revision: Union[str, Sequence[str], None] = "6c4b796bd8ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
