"""update job model

Revision ID: 7d8392a7960e
Revises: 7e6d024de6e3
Create Date: 2026-07-12 18:33:59.098152

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7d8392a7960e"
down_revision: Union[str, Sequence[str], None] = "7e6d024de6e3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("jobs", sa.Column("city", sa.String(length=100), nullable=False))
    op.add_column("jobs", sa.Column("address", sa.String(length=255), nullable=False))
    op.drop_column("jobs", "location")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "jobs",
        sa.Column(
            "location", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("jobs", "address")
    op.drop_column("jobs", "city")
    # ### end Alembic commands ###
