"""add online status

Revision ID: b3fc2f039b67
Revises: 51833484f818
Create Date: 2026-07-16 20:33:55.947918

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b3fc2f039b67"
down_revision: Union[str, Sequence[str], None] = "51833484f818"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("is_online", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "users", sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "last_seen")
    op.drop_column("users", "is_online")
    # ### end Alembic commands ###
